# Generated by Django 4.1.7 on 2024-11-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceXpress', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
