# Generated by Django 5.1.3 on 2024-11-12 16:30

import ServiceXpress.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceXpress', '0009_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Only alphabetical characters and spaces are allowed.', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='service_media/', validators=[ServiceXpress.models.validate_file_extension, ServiceXpress.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabetical characters and spaces are allowed.', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabetical characters and spaces are allowed.', regex='^[A-Za-z\\s]*$')]),
        ),
    ]
